import {
    useState
} from 'react'
import Treg from './img/answer/Treg.png';
import TLRpattern from './img/answer/TLRpattern.png';
import TLR from './img/answer/TLR.png';
import ThDifferentiation from './img/answer/ThDifferentiation.png';
import Th17 from './img/answer/Th17.png';
import TcellGammaDelta from './img/answer/TcellGammaDelta.png';
import TcellEducation from './img/answer/TcellEducation.png';
import TcellDifferentiation from './img/answer/TcellDifferentiation.png';
import TcellActivationSignal from './img/answer/TcellActivationSignal.png';
import superantigen from './img/answer/superantigen.png';
import RLR from './img/answer/RLR.png';
import PerforinGranzyme from './img/answer/PerforinGranzyme.png';
import LPS from './img/answer/LPS.png';
import invariantChain from './img/answer/invariantChain.png';
import crossPresentation from './img/answer/crossPresentation.png';
import centralMemoryT from './img/answer/centralMemoryT.png';
import TCRSegments from './img/answer/TCRSegments.png';
import TI1antigen from './img/answer/TI1antigen.png';
import RSS from './img/answer/RSS.png';
import RAG from './img/answer/RAG.png';
import Nivolumab from './img/answer/Nivolumab.png';
import IL2 from './img/answer/IL2.png';
import IL1Beta from './img/answer/IL1Beta.png';
import epitope from './img/answer/epitope.png';
import CART from './img/answer/CART.png';
import BCellImmature from './img/answer/BCellImmature.png';
import antibodyGraph from './img/answer/antibodyGraph.png';
import AIRE from './img/answer/AIRE.png';
import receptorEditing from './img/answer/receptorEditing.png';  






// import from './img/answer/.png'

export const useQuestionList = () => {
    const appName = 'anywhere-immunology'
    const jpName = '免疫学'
    const [questionList, setQuestionList] = useState([
        // ここに問題のリストを記述(選択式の場合は[0]に正解択をいれた配列をつくる)
        {
            groupTag: '2021本試験一問一答',
            groupContents: [{
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '炎症の4徴候について、誤っているものを2つ選べ。',
                    choices: ['浮腫', '壊死', '発赤', '熱感', '疼痛', '腫脹'],
                    answerImg: [],
                    answer: '浮腫、壊死',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '原発性免疫不全症候群の特徴について、誤っているものを2つ選べ。',
                    choices: [
                        'Chediak-Higashi症候群 - 急性転化',
                        'Wiskott-Aidrich症候群 - 血小板減少',
                        'Digeorge症候群 - 低カルシウム血症',
                        'X連鎖無ガンマグロブリン血症 - ATM変異',
                        '慢性肉芽腫症 - ペルオキシダーゼ陽性巨大顆粒',
                        '毛細血管拡張性運動失調症 - 体幹失調',
                    ],
                    answerImg: [],
                    answer: 'X連鎖無ガンマグロブリン血症　慢性肉芽腫症',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'PRRが認識するPAMPsと病原体の組み合わせについて、誤っているものを2つ選べ。',
                    choices: [
                        'TLR2 - リポポリサッカライドLPS - 大腸菌',
                        'TLR5 - フラジェリン - 大腸菌',
                        'TLR9 - ペプチドグリカン - 大腸菌',
                        'RIG-I  - RNAウイルス - インフルエンザウイルス',
                        'Dectin-1 - βグルカン - カンジダ',
                        'Mincle - トレハロースジミコール酸TDM - 結核菌',
                    ],
                    answerImg: [TLR],
                    answer: 'TLR2　TLR9',
                    commentary: 'TLR2はグラム陽性菌、TLR9は細菌DNAを主に認識する。大腸菌はグラム陰性（鞭毛あり）',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'T細胞の胸腺分化について、誤っているものを2つ選べ。',
                    choices: [
                        'γδT細胞の遺伝子再構成はαβT細胞の遺伝子再構成に先行する',
                        '正の選択の後に負の選択が起こる',
                        '正の選択は胸腺皮質で、負の選択は胸腺髄質で行われる。',
                        '正の選択の際にMHCクラスⅡ分子に提示されたペプチドを認識した細胞はCD8陽性T細胞へと分化する。',
                        '正の選択はダブルポジディブ期に起こる',
                        'AIRE(Autoimmune regulator)は隔絶抗原を発現することで負の選択に関与している。',
                    ],
                    answerImg: [AIRE],
                    answer: '正の選択の際にMHCクラスⅡ分子に提示されたペプチドを認識した細胞はCD8陽性T細胞へと分化する。　AIRE(Autoimmune regulator)は隔絶抗原を発現することで負の選択に関与している。',
                    commentary: 'MHC class2 → CD8+T細胞、AIREはゲノムにコードされた自己抗原を無差別発現する',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '免疫組織化学染色について、誤っているものを2つ選べ。',
                    choices: [' 酵素抗体染色は光学顕微鏡で観察できる。', '酵素抗体染色は永久標本が作れる。 ', '直接法は間接法より感度が高い。 ', '脱パラフィンにはキシレンが頻用される。 ', '内因性ペルオキシダーゼは赤血球や顆粒球に存在する。 ', '内因性ペルオキシダーゼの不活化にはエタノールを用いる。'],
                    answerImg: [],
                    answer: '直接法は間接法より感度が高い。　内因性ペルオキシダーゼの不活化にはエタノールを用いる。',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '移植免疫について、誤っているものを2つ選べ。',
                    choices: ['HLA 一致の兄弟間では拒絶反応は起こらない。  ', ' 超急性拒絶は主に既存抗原が補体依存性に内皮傷害を生じることで起こる。 ', '急性拒絶は主に T 細胞によるものである。 ', '慢性拒絶の病理学的特徴は血管肥厚による閉塞と線維化である。 ', '急性 GVHD の主な対象臓器は皮膚、肝臓、消化器である。 ', '急性 GVHD はレシピエントの T 細胞が移植片に対して拒絶反応を示すことで起きる。 '],
                    answerImg: [],
                    answer: '慢性拒絶の病理学的特徴は血管肥厚による閉塞と線維化である。 　急性 GVHD はレシピエントの T 細胞が移植片に対して拒絶反応を示すことで起きる。 ',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '自己免疫疾患について、誤っているものを2つ選べ。',
                    choices: ['自己免疫疾患は微生物感染によって引き起こされうる。 ', 'Basedow 病は、甲状腺ホルモンに自己抗体が作られることによるⅤ型アレルギーである。 ', 'Ⅰ型糖尿病は、膵β細胞に対する CD8 陽性 T 細胞が強く関与している。  ', '強直性脊椎炎は HLA-B27 の多型によるもので、女性に多い。 ', '多発性筋炎/皮膚筋炎では自己抗体である抗 Jo-1 抗体の上昇を認める。 ', '関節リウマチの診断で、リウマチ因子(Rheumatoid Factor)は抗 CCP 抗体よりも特異性が低い。 '],
                    answer: 'Basedow 病は、甲状腺ホルモンに自己抗体が作られることによるⅤ型アレルギーである。　強直性脊椎炎は HLA-B27 の多型によるもので、女性に多い。 ',
                    commentary: '',
                    answerImg: [],
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '免疫寛容について、誤っているものを2つ選べ。',
                    choices: ['中枢性寛容と末梢性寛容は相互補完的に働くため、一方の破綻だけでは自己免疫疾患を発症しない。 ', '通常、食物抗原に対しては経口寛容が成立しているため、免疫応答は起こらない。 ', '制御性 T 細胞 (Treg) は CTLA-4 を高発現しており、CD28 と CD80/CD86 の結合を競合的に阻害することで T 細胞の活性化を抑制する。 ', 'Treg は IL-2 Rα鎖(CD25) を発現しているため、 ナイーブT細胞より IL-2 に対する反応性が高い。 ', 'Treg は IL-10、TGF-βなど抑制性サイトカインを産生し、T細胞の活性化を抑制する。', 'IPEX 症候群は、Treg の分化に必須の転写因子 T-bet の遺伝子異常により発症する。'],
                    answerImg: [Treg],
                    answer: '中枢性寛容と末梢性寛容は相互補完的に働くため、一方の破綻だけでは自己免疫疾患を発症しない。  IPEX 症候群は、Treg の分化に必須の転写因子 T-bet の遺伝子異常により発症する。',
                    commentary: '中枢・末梢どちらの免疫寛容が破綻しても自己免疫疾患の原因となるIPEX症候群に関わる、Treg の分化に必須の遺伝子はFoxp3',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '腫瘍免疫について、誤っているものを2つ選べ。',
                    choices: ['がん細胞ではMHCに変異が蓄積しており、免疫系によって自己と認識されない', '免疫チェックポイント阻害薬は正の選択と負の選択の調整を行う', '腫瘍細胞はPD-L1を発現し免疫監視からの逃避機構を獲得している', 'CAR-T療法の標的は固形腫瘍である'],
                    answerImg: [Nivolumab, CART],
                    answer: '2と4が誤り',
                    commentary: 'ミスマッチ修復機構の欠損などが原因で変異を繰り返したがん細胞はもはや自己の細胞とは認識されなくなっており、リンパ球が浸潤していることが多いが、多くのがん細胞はPD-L1(免疫チェックポイント機構)を発現することでT細胞による排除から逃れている。このPD-L1はT細胞上のPD-1に対するリガンドであり正の選択や負の選択（T細胞のセレクション）とは無関係である。CAR-T療法は患者のT細胞にCAR遺伝子を導入し患者に戻すがん治療法であるが、固形がんにはハードルが高い。主な対象は白血病などの血球系がん→薬品名：キムリア。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'サイトカインについて、誤っているものを2つ選べ。',
                    choices: ['IL-1β前駆体はプロテアソームによって切断され成熟する。', 'IL-2 は T細胞、NK細胞の分化を促進するが B細胞の活性化は抑制する。', 'IL-12 は IFN-γの産生を促し Th1 細胞の分化を促進する。', 'IL-15 は NK 細胞を分化、増殖させる。 ', 'IL-17 の過剰分泌は上皮細胞を増殖させ、尋常性乾癬を引き起こす。 ', 'IL-33 は内皮細胞の傷害によって産生され、自然リンパ球 ILC2 の分化を促進する。 '],
                    answer: '2と6が誤り',
                    answerImg: [IL1Beta, IL2, ThDifferentiation],
                    commentary: 'IL-1βの成熟には（TLRなどの刺激→）前駆体の生成と、（NLRの活性化→）ICE:IL-1β converting enzymeによる前駆体の切断が必要。IL-2はB細胞の活性化にも働く',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '遺伝子再構成について、誤っているものを2つ選べ。',
                    choices: ['12 塩基と 23 塩基の配列が近接した RSS を RAG-1,2 が認識して切断する。 ', 'TdT はプロ細胞期に発現するため、L 鎖よりも H 鎖の方が接合部多様性が高い。', 'L 鎖ではκ鎖とλ鎖の遺伝子再構成が同時に起こる。 ', ' 遺伝子再構成は骨髄において行われ、多様性を獲得する。 ', '接合部多様性は主に CDR3 の領域に存在する。 ', 'レセプター編集とは、CRISPR/Cas9 により L鎖遺伝子が再構成されることである。 '],
                    answerImg: [RSS, RAG, BCellImmature, receptorEditing],
                    answer: '3と6が誤り',
                    commentary: 'RSS(Recombination Signal Sequence/組み換え認識配列)はVセグメント・Dセグメント・Jセグメントの間にある数十bpの配列で、遺伝子再構成の際の切り出し部分のターゲットとなっている。切り出しにはRAG-1,2(Recombination Activating Gene/VDJ組み換え酵素)によって引き起こされ、切られたDNA末端はArtemisやTdT(Terminal Deoxynucleotidyl Transferase/末端ヌクレオチド付加酵素)によって変異に富む修復を受ける。B細胞の遺伝子再構成は骨髄で行われる。遺伝子再構成はH鎖遺伝子→L鎖遺伝子(κ→λ)の順に行われるが、遺伝子再構成がうまくいかなかった場合はL鎖遺伝子で新たな遺伝子再構成が行われる→レセプター編集:Receptor Editing',
                },

                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '抗体について、誤っているものを2つ選べ。',
                    choices: ['抗体は血清タンパク質を電気泳動したときのγグロブリン分画に存在する。 ', '膜型の IgM と IgD は単一の成熟 B 細胞で同時に発現する。 ', '抗体をペプシン分解すると 2 つの Fab と 1 つの Fc に分かれる。 ', '成熟した B 細胞は膜型抗体と分泌型抗体をつくる。 ', 'IgM は 5 量体であるので、抗原と結合する部位は 10 箇所ある。 ', '血清中の IgG が最も多いのは、IgG が自然抗体として産生されるからである。'],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '粘膜免疫について、誤っているものを2つ選べ。',
                    choices: ['M 細胞は抗原を貪食し、パイエル板を介して T 細胞に抗原を提示する。 ', 'リンパ球はレチノイン酸によって粘膜固有層にホーミングされる。', '樹状細胞の産生する TGF-βにより制御性 T 細胞と Th17 細胞が生じる', ' 粘膜で抗原の免疫寛容を誘導すれば、全身性の免疫寛容をもたらす。 ', '経口免疫の方が、経皮免疫より免疫寛容を誘導しやすい。 ', '免疫寛容を獲得した人の血清を別の人に注射した場合、免疫寛容が誘導される。 '],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '膜侵襲複合体(MAC)の形成を直接抑制する分子を2つ選べ。',
                    choices: ['B因子', 'CD59', 'CD46', 'H因子', 'I因子', 'Sタンパク質'],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'HLAに関連した疾患で、オッズ比が1000以上のものをを2つ選べ。',
                    choices: ['Ⅰ型糖尿病', '潰瘍性大腸炎', 'ナルコレプシー', '関節リウマチ', '強直性脊椎炎', 'Behçet病'],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                // {
                //     detailInfo: '',
                //     questionImg: [],
                //     questionSentence: '抗原提示について、誤っているものを2つ選べ。',
                //     choices: ['', '', '', '', '', ''],
                //     answerImg: [],
                //     answer: '',
                //     commentary: '',
                // },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '生殖免疫について、誤っているものを2つ選べ。',
                    choices: ['HLA-E は NK レセプターCD94/NKG2C で NK 細胞を活性化させ、サイトカイン放出を促進する。 ', 'NK 細胞は一つの細胞上に KAR と KIR を持つ。 ', '胎盤トロホブラストには CD55 があり、父由来 HLA に対する遮断抗体として働く。 ', '妊娠初期には M1 マクロファージは M2 マクロファージより多い ', '胎盤脱落膜上には制御性 T 細胞が増加し、胎児の父系抗原特異的な反応を制御している。 ', '脱落膜 NK 細胞のほとんどは CD56 弱陽性 NK 細胞である。 '],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '感染症について、誤っているものを2つ選べ。',
                    choices: ['肺炎球菌やインフルエンザ菌など、莢膜を持つ細菌の貪食にはオプソニンが重要である。', '結核診断には結核特異的な抗体の抗体価を測定するのが有効である。 ', ' 結核性胸膜炎において、胸水中の ADA 活性上昇が認められる。 ', '寄生虫 (蠕虫) 感染では好酸球増加と IgE 上昇が起こる。 ', ' HIV 感染症で、CD４陽性 T 細胞数が 200/mm3 を下回ると日和見感染症、腫瘍などの AIDS 指標疾患を発症しやすくなる。 ', 'SARS-CoV-2 は気道の上皮細胞に感染し、他の上皮細胞には感染しない。 '],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                // {
                //   detailInfo: '',
                //   questionImg: [],
                //   questionSentence: 'について、誤っているものを2つ選べ。',
                //   choices: ['', '', '', '', '', ''],
                //   answerImg: [],
                //   answer: '',
                //   commentary: '',
                // },
                // {
                //     detailInfo: '',
                //     questionImg: [],
                //     questionSentence: 'について、誤っているものを2つ選べ。',
                //     choices: ['', '', '', '', '', ''],
                //     answerImg: [],
                //     answer: '',
                //     commentary: '',
                // },
                // {
                //   detailInfo: '',
                //   questionImg: [],
                //   questionSentence: 'について、誤っているものを2つ選べ。',
                //   choices: ['', '', '', '', '', ''],
                //   answerImg: [],
                //   answer: '',
                //   commentary: '',
                // },
                // {
                //     detailInfo: '',
                //     questionImg: [],
                //     questionSentence: 'について、誤っているものを2つ選べ。',
                //     choices: ['', '', '', '', '', ''],
                //     answerImg: [],
                //     answer: '',
                //     commentary: '',
                // },
                // {
                //   detailInfo: '',
                //   questionImg: [],
                //   questionSentence: 'について、誤っているものを2つ選べ。',
                //   choices: ['', '', '', '', '', ''],
                //   answerImg: [],
                //   answer: '',
                //   commentary: '',
                // },
                // {
                //     detailInfo: '',
                //     questionImg: [],
                //     questionSentence: 'について、誤っているものを2つ選べ。',
                //     choices: ['', '', '', '', '', ''],
                //     answerImg: [],
                //     answer: '',
                //     commentary: '',
                // },
                // {
                //   detailInfo: '',
                //   questionImg: [],
                //   questionSentence: 'について、誤っているものを2つ選べ。',
                //   choices: ['', '', '', '', '', ''],
                //   answerImg: [],
                //   answer: '',
                //   commentary: '',
                // },
                // {
                //     detailInfo: '',
                //     questionImg: [],
                //     questionSentence: 'について、誤っているものを2つ選べ。',
                //     choices: ['', '', '', '', '', ''],
                //     answerImg: [],
                //     answer: '',
                //     commentary: '',
                // },
                // {
                //   detailInfo: '',
                //   questionImg: [],
                //   questionSentence: 'について、誤っているものを2つ選べ。',
                //   choices: ['', '', '', '', '', ''],
                //   answerImg: [],
                //   answer: '',
                //   commentary: '',
                // },
                // {
                //     detailInfo: '',
                //     questionImg: [],
                //     questionSentence: 'について、誤っているものを2つ選べ。',
                //     choices: ['', '', '', '', '', ''],
                //     answerImg: [],
                //     answer: '',
                //     commentary: '',
                // },
                // {
                //   detailInfo: '',
                //   questionImg: [],
                //   questionSentence: 'について、誤っているものを2つ選べ。',
                //   choices: ['', '', '', '', '', ''],
                //   answerImg: [],
                //   answer: '',
                //   commentary: '',
                // },
                // {
                //     detailInfo: '',
                //     questionImg: [],
                //     questionSentence: 'について、誤っているものを2つ選べ。',
                //     choices: ['', '', '', '', '', ''],
                //     answerImg: [],
                //     answer: '',
                //     commentary: '',
                // },
                // {
                //   detailInfo: '',
                //   questionImg: [],
                //   questionSentence: 'について、誤っているものを2つ選べ。',
                //   choices: ['', '', '', '', '', ''],
                //   answerImg: [],
                //   answer: '',
                //   commentary: '',
                // },

                // {
                //   detailInfo: '',
                //   questionImg: [],
                //   questionSentence: 'について、誤っているものを2つ選べ。',
                //   choices: ['', '', '', '', '', ''],
                //   answerImg: [],
                //   answer: '',
                //   commentary: '',
                // },
                // {
                //   detailInfo: '',
                //   questionImg: [],
                //   questionSentence: 'について、誤っているものを2つ選べ。',
                //   choices: ['', '', '', '', '', ''],
                //   answerImg: [],
                //   answer: '',
                //   commentary: '',
                // },
            ],
        }, {
            groupTag: "2022本試験一問一答",
            groupContents: [{
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '気管支喘息の特徴はどれか',
                    choices: ['気管支平滑筋の増生', ' 粘液の分泌低下', '気管支粘膜の？？', 'IL-5 による好中球増多', 'IL-12 による自然リンパ球増多'],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '免疫グロブリン(IgG)の抗原認識部位を構成するものは？',
                    choices: ['H鎖の3つの超可変ループ', 'L 鎖の3つの超可変ループ', '6つの超可変ループ：H鎖とL鎖のそれぞれ3つの超可変ループが一つずつ', '6つの超可変ループ：H鎖の3つの超可変ループが二つ', '12個の超可変ループ：H鎖とL鎖それぞれ3つの超可変ループが二つずつ'],
                    answerImg: [epitope],
                    answer: '6つの超可変ループ：H鎖とL鎖のそれぞれ3つの超可変ループが一つずつ',
                    commentary: 'Igドメインは2層のβシートによる球状の構造をしていて、抗体それぞれで配列が異なっている → 超可変領域:hypervariable regionとよばれる。超可変領域はH鎖とL鎖ともに3つ存在する。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'T細胞非依存性抗原によって産生される免疫グロブリンのタイプは？ ',
                    choices: ['IgE', 'IgD', 'IgM', 'IgA', 'IgG'],
                    answerImg: [TI1antigen],
                    answer: 'IgM',
                    commentary: 'タンパク抗原に対する抗体産生応答には、抗原特異的なTh細胞による補助が必要であるが、TLRのリガンドとなる部分を持つような抗原：TI-1抗原（LPS・DNA・RNA）や細菌細胞壁の多糖のようなきわめて反復性の高い構造：TI-2抗原（細菌莢膜・多糖類）などはT細胞非依存性抗原で、B細胞を直接活性化させ、主にIgMを産生する。（一部IgGを産生する場合もある）',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '新型コロナワクチンの追加接種の 3 週間後にどのサブクラスが増加しているか。',
                    choices: ['IgA', 'IgD', 'IgE', 'IgG', 'IgM'],
                    answerImg: [antibodyGraph],
                    answer: 'IgG',
                    commentary: '即時にIgMが産生されるが、時間とともにIgGが増えていく',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '新しく産生された MHC クラスⅡに内在性ペプチドが結合することを防ぐものを選べ。',
                    choices: ['インバリアント鎖', 'CLIP', 'HLA-DM', '', '', ''],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'MHC クラスⅠの提示経路で、タンパク質分解処理のために結合する分子はどれか。',
                    choices: ['カルネティキュリン', 'ペプシン', 'タパシン', 'ユビキチン', 'カルネキシリン'],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '次のうち、T細胞が発現していないものを選べ',
                    choices: ['CD3', 'CD4', 'CD8', 'CD28', 'CD86'],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'シグナル伝達の時の生化学的反応を選べ',
                    choices: ['グリコシル化', 'チロシンリン酸化', 'ユビキチン化', 'アセチル化', 'メチル化'],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'ナイーブT細胞が二次リンパ組織へ遊走するときに必要な分子を選べ',
                    choices: ['CCR7-Lセレクチン', 'CXCR3', 'CXCR5', 'CXCR7', 'CTLR4'],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'HIVが侵入する際に直接関係しないのは？',
                    choices: ['CD4', 'MHCクラス1', 'CCR5', 'CXCR4', 'エンベロープ'],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '1ワクチンで撲滅したウイルスは？',
                    choices: ['ポリオ', '風疹', '結核', '天然痘', '破傷風'],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'T細胞の機能不全と関係のない疾患は？',
                    choices: ['がん', 'ウイルス感染', '自己免疫疾患', '結核菌感染', '黄色ブドウ球菌感染'],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },

                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'どのレシピエントにも輸血が可能なドナーの血液型とは？',
                    choices: ['A型', 'B型', 'AB型', 'O型', 'Rh+型'],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '腎移植した血小板の抗原の抗体を持っている場合における拒絶反応についての問い',
                    choices: ['数分でヤバイ', '数時間でヤバイ', '数日でヤバイ', '日和見何たら', ''],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '二回目の妊娠、母親はO型Rh-、父オアはO型Rh+、胎児が陥る可能性のある疾患',
                    choices: ['1型アレルギー早期', 'Ⅰ型アレルギー後期', 'Ⅱ型アレルギー', 'Ⅲ型アレルギー', 'Ⅳ型アレルギー'],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '13歳の男児が蜂に刺され、数分後にショック状態となった。この説明として正しいのはどれか？',
                    choices: ['', '', '', '', ''],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '',
                    choices: ['', '', '', '', ''],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '',
                    choices: ['', '', '', '', ''],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '',
                    choices: ['', '', '', '', ''],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '',
                    choices: ['', '', '', '', ''],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '',
                    choices: ['', '', '', '', ''],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '',
                    choices: ['', '', '', '', ''],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '',
                    choices: ['', '', '', '', ''],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '',
                    choices: ['', '', '', '', ''],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '',
                    choices: ['', '', '', '', ''],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '',
                    choices: ['', '', '', '', ''],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '',
                    choices: ['', '', '', '', ''],
                    answerImg: [],
                    answer: '',
                    commentary: '',
                },
                // {
                //   detailInfo: '',
                //   questionImg: [],
                //   questionSentence: '',
                //   choices: ['', '', '', '', ''],
                //   answerImg: [],
                //   answer: '',
                //   commentary: '',
                // },
            ]
        },
        {
            groupTag: '授業中',
            groupContents: [{
                    detailInfo: '4/07 N県立医科大学後期入試問題（生物）',
                    questionImg: [],
                    questionSentence: '免疫は大きく、自然免疫と獲得免疫（適応免疫）に分けられる。自然免疫に関わる細胞には、組織中にとどまっている（ 1 ）、があり、主に食作用により微生物を処理する。獲得免疫を担う細胞免疫には、（ 2 ）や（ 3 ）があり、あわせて（ 4 ）という。(2)は主に、（ 5 ）から抗原提示を受けてインターロイキンなどの刺激物質を分泌することで（3）に働きかけ、抗体を分泌する（ 6 ）に分化させる。（2）にはウイルス感染細胞を直接攻撃し破壊するものもいる。獲得免疫のうち、抗体が関与する免疫を（ 7 ）免疫といい、（2）が直接標的細胞を殺すことを（ 8 ）免疫という。',
                    answerImg: [],
                    answer: '1.マクロファージ　2.T細胞　3.B細胞　4.リンパ球　5.樹状細胞　6.形質細胞　7.体液性　8.細胞性　',
                    commentary: '',
                },
                {
                    detailInfo: '4/07',
                    questionImg: [],
                    questionSentence: '白血球の正常値は？',
                    choices: ['5/μL', '50/μL', '500/μL', '5000/μL', '50000/μL'],
                    answerImg: [],
                    answer: '5000/μL',
                    commentary: '正常値は4000~9000個/μL,3000は少なく、10000は多いイメージ',
                },
                {
                    detailInfo: '4/07',
                    questionImg: [],
                    questionSentence: '体重65kgの人間の体内には、白血球はどのくらいの数存在しているか？（白血球の正常値は5000個/μL）',
                    answerImg: [],
                    answer: '250億個',
                    commentary: '5000 * 1000000(μL→L) * 5(5Lの血液)',
                },
                {
                    detailInfo: '4/07　出席確認',
                    questionImg: [],
                    questionSentence: '炎症の5徴として正しいのはどちらか',
                    choices: ['浮腫', '腫脹'],
                    answerImg: [],
                    answer: '腫脹',
                    commentary: '漢字間違いが多い。5徴はほかに熱感heat・発赤redness・疼痛swelling・機能障害dysfunction',
                },
                {
                    detailInfo: '4/14　小テスト',
                    questionImg: [],
                    questionSentence: 'サイトカインの特徴として正しいのはどちらか',
                    choices: ['低分子', '高分子'],
                    answerImg: [],
                    answer: '低分子',
                    commentary: 'サイトカインは低分子（分子量三万前後）の糖たんぱく質(glycoprotein)であり、多くは糖鎖を持つ。きわめて微量で効果を発揮する。',
                },
                {
                    detailInfo: '4/14　小テスト',
                    questionImg: [],
                    questionSentence: 'サイトカインの主なシグナル伝達経路として正しいのはどちらか',
                    choices: ['JAK/STAT', 'Notch'],
                    answerImg: [],
                    answer: 'JAK/STAT',
                    commentary: 'ほとんどのサイトカイン受容体はⅠ型・Ⅱ型受容体を介して信号を伝達する。これらはJAK/STAT経路によって標的遺伝子の転写を誘導する。JAKファミリーは4種類、STATは7種類存在する。',
                },
                {
                    detailInfo: '4/14　小テスト',
                    questionImg: [],
                    questionSentence: '抑制性サイトカインとして正しいのはどちらか',
                    choices: ['IL-6', 'IL-10'],
                    answerImg: [],
                    answer: 'IL-10',
                    commentary: '抑制性サイトカインIL-10は、Th2細胞から産生されるTh1抑制因子（その他免疫寛容IgAにも関与する）として同定された。抑制性サイトカインは他にTGF-β（活性化マクロファージや制御性T細胞などが産生する）しか存在しない。炎症性のサイトカインとしてIL-1、TNF、IL-6が挙げられる。',
                },
                {
                    detailInfo: '4/14　小テスト',
                    questionImg: [],
                    questionSentence: '抗原提示能が高いのはどちらか',
                    choices: ['マクロファージ', '樹状細胞'],
                    answerImg: [],
                    answer: '樹状細胞',
                    commentary: '抗原提示細胞として樹状細胞・マクロファージ・B細胞の3つが存在し、自然免疫と獲得免疫の架け橋を担っているが、その中で最も抗原提示能が高いのは樹状細胞。マクロファージは貪食能（大食細胞とよばれる）・殺菌能が高い。',
                },
                {
                    detailInfo: '4/14　小テスト',
                    questionImg: [],
                    questionSentence: 'Pattern Recognition Receptor（パターン認識受容体）として正しいのはどちらか',
                    choices: ['ACE2 Receptor', 'Toll-like Receptor'],
                    answerImg: [TLR],
                    answer: 'TLR/Toll-like Receptor',
                    commentary: 'TLRは最も有名なPRRで、PRRの代表格である。',
                },
                {
                    detailInfo: '4/14　小テスト',
                    questionImg: [],
                    questionSentence: '抗ウイルス作用が高いサイトカインとして正しいのはどちらか',
                    choices: ['IFN-α', 'IFN-γ'],
                    answerImg: [],
                    answer: 'IFN-α',
                    commentary: 'Ⅰ型IFNで、細胞を抗ウイルス状態にする。',
                },
                {
                    detailInfo: '4/14　小テスト',
                    questionImg: [],
                    questionSentence: 'ケモカインの定義として正しいのはどちらか',
                    choices: [
                        '白血球遊走に関わるサイトカイン',
                        '白血球活性化に関わるサイトカイン',
                    ],
                    answerImg: [],
                    answer: '白血球遊走に関わるサイトカイン',
                    commentary: 'chemotactic(走化性) + cytokine（サイトカイン）ケモカインは後にIL-8として命名される。',
                },
                {
                    detailInfo: '4/14　小テスト',
                    questionImg: [],
                    questionSentence: 'Th1細胞が産生するサイトカインとして正しいのはどちらか',
                    choices: ['IL-12', 'IFN-γ'],
                    answerImg: [],
                    answer: 'IFN-γ',
                    commentary: 'ヘルパーT細胞の分化を決定する最も重要な因子はサイトカイン環境。Th0(naive T cell)→Th1...IFN-γを産生し細菌・ウイルスを標的とするヘルパーT細胞への分化にはIL-12が必要。よって、Th1が産生するサイトカインはIFN-γ。他にもTh-4...IL-4などを産生し寄生虫を標的とするヘルパーT細胞への分化にはIL-4が必要で、ヘルパーT細胞の分化誘導にはサイトカインが深くかかわっている。',
                },
                {
                    detailInfo: '4/14　小テスト',
                    questionImg: [],
                    questionSentence: '血球とサイトカインの組み合わせで正しいのはどちらか',
                    choices: ['赤血球-エリスロポエチン', '好中球-トロンボポエチン'],
                    answerImg: [],
                    answer: '赤血球-エリスロポエチン',
                    commentary: 'エリスロポエチンは腎臓から産生され赤血球への分化に造血系サイトカイン。トロンボポエチンは肝臓由来の血小板への分化に必要な造血系サイトカイン。G-CSF(Granulocyte colony-stimulating factor)は骨髄の間質形細胞・血管内皮細胞などが産生し好中球への分化に必要な造血系サイトカイン。',
                },
                {
                    detailInfo: '4/14　小テスト',
                    questionImg: [],
                    questionSentence: '誤っているサイトカイン-微生物の組み合わせを2つ選べ。',
                    choices: [
                        'TLR2-肺炎レンサ球菌',
                        'TLR3-緑膿菌',
                        'TLR4-大腸菌',
                        'TLR5-ヘリコバクターピロリ菌',
                        'RIG-I - インフルエンザ菌',
                        'NOD1-リステリア菌',
                    ],
                    answer: 'TLR3、RIG-I',
                    answerImg: [TLRpattern],
                    commentary: 'ヘリコバクターピロリ菌は鞭毛がある→フラジェリンと結合するので、TLR5の選択肢は正しい。インフルエンザはウイルスなので、RIG-Iとの組み合わせは当たっているが、インフルエンザ菌ではない。その他、大腸菌はグラム陰性菌でTLR4、肺炎連鎖球菌はグラム陽性菌でTLR2。',
                },
                {
                    detailInfo: '4/14',
                    questionImg: [],
                    questionSentence: '血球とサイトカインの組み合わせで正しいのはどれか。3つ選べ',
                    choices: [
                        '好中球-G-CSF',
                        '好酸球-IFNα',
                        'Tリンパ球-IL-2',
                        '赤血球-エリスロポエチン',
                        '血小板-IL-4',
                    ],
                    answer: '好中球、Tリンパ球、赤血球',
                    commentary: '好酸球へはIL-5で分化が誘導される。エリスロポエチンは腎臓で産生される。',
                },
                {
                    detailInfo: '4/21特別講義',
                    questionImg: [],
                    questionSentence: '炎症の５主徴として誤っているものはどれか？（資料8枚目）',
                    answerImg: [],
                    choices: ['Redness', 'Swelling', 'Edema', 'Pain', 'Dysfunction'],
                    answer: 'Edema',
                    commentary: '浮腫Edemaではなく腫脹swelling',
                },
                {
                    detailInfo: '4/21特別講義',
                    questionImg: [],
                    questionSentence: 'がんの10年生存率として最も適切なのはどれか？（資料80枚目）            ',
                    answerImg: [],
                    choices: ['約10%', '約20%', '約40%', '約60%', '約80%'],
                    answer: '約60%',
                    commentary: '5年生存率・10年生存率は前立腺がんなら90%以上、乳がんでも80%以上',
                },
                {
                    detailInfo: '4/28　小テスト',
                    questionImg: [],
                    questionSentence: '小胞体内でインバリアント鎖が結合しているのは次のどちらか？    ',
                    answerImg: [invariantChain],
                    choices: ['MHCクラスI分子', 'MHCクラスII分子'],
                    answer: 'MHCクラスII分子',
                    commentary: '',
                },
                {
                    detailInfo: '4/28　小テスト',
                    questionImg: [],
                    questionSentence: 'クロスプレゼンテーションによる抗原提示が行われるのはどちらか            ',
                    answerImg: [crossPresentation],
                    choices: [
                        '外来性抗原をCD8T細胞に提示する',
                        '内在性抗原をCD8T細胞に提示する',
                    ],
                    answer: '外来性抗原をCD8T細胞に提示する',
                    commentary: 'その他、パターン認識レセプターによる外来性抗原の取り込みも、断片化されればCD8陽性T細胞に抗原提示することができる',
                },
                {
                    detailInfo: '4/28　小テスト',
                    questionImg: [],
                    questionSentence: '脂質抗原を提示するのは次のどちらでしょうか',
                    answerImg: [],
                    choices: ['CD1d', 'MICA'],
                    answer: 'CD1d',
                    commentary: 'テスト本番でもMHC Class1c　ではなく、CD1dまたはMICAとして解答してほしい',
                },
                {
                    detailInfo: '5/12 出席確認',
                    questionImg: [],
                    questionSentence: '日本で初めてノーベル医学・生理学賞を受賞したのは誰か？',
                    answerImg: [],
                    answer: '利根川進',
                    commentary: '',
                },
                {
                    detailInfo: '5/12 出席確認',
                    questionImg: [],
                    questionSentence: '抗体のクラスと機能の組み合わせとして誤っているものを選べ',
                    answerImg: [],
                    choices: ["IgM：補体活性化", "IgM：オプソニン化", "IgA：粘膜面での中和", "IgG：血清中での中和", "IgG：抗体依存性細胞障害活性", "IgE：アレルギー反応"],
                    answer: 'IgM：オプソニン化',
                    commentary: '誤っているというよりは最適ではないもの。オプソニン化はIgGの役割のほうが大きい。',
                },
                {
                    detailInfo: '5/12 出席確認',
                    questionImg: [],
                    questionSentence: '【正誤問題】抗体の多様性はIgGの転写産物のスプライシングによって生み出される',
                    answerImg: [],
                    answer: '誤り',
                    commentary: '参考:VDJリコンビネーション、遺伝子再構成',
                },
                {
                    detailInfo: '5/12 出席確認',
                    questionImg: [],
                    questionSentence: '【正誤問題】一つのB細胞は、2本の染色体に由来する２種類の抗体分子を発現する',
                    answerImg: [],
                    answer: '誤り',
                    commentary: '1つのB細胞に対して1種類の抗体の原則。',
                },
                {
                    detailInfo: '0519レジュメ中',
                    questionImg: [],
                    questionSentence: '胸腺におけるT細胞分化について誤っているものを2つ選べ。',
                    choices: ["負の選択とは自己抗原と過剰に反応するT細胞を排除することである",
                        "正の選択とは自己抗原と適度に反応するT細胞を残すことである",
                        "負の選択は胸腺皮質、正の選択は胸腺髄質でおこる",
                        "核内蛋白AIRE(autoimmune regulator)は種々の自己抗原を産生し、負の選択に寄与する",
                        "CD8+T細胞はCD4+CD8+T細胞 → CD4-CD8-T細胞 → CD8+T細胞の経過をたどり分化する ",
                        "T細胞の遺伝子再構成はCD4-CD8-T細胞の段階から行われる"
                    ],
                    answerImg: [TcellDifferentiation, TcellEducation],
                    answer: '3と5は誤り...正の選択は胸腺皮質、負の選択は胸腺髄質で行われる。CD4-CD8-(Double Negative)T細胞 → CD4+CD8+(Double Positive)T細胞 の順番',
                    commentary: '特にβ鎖はDouble Negativeの段階から行われる。',
                },
                {
                    detailInfo: '0519レジュメ中',
                    questionImg: [],
                    questionSentence: 'T細胞の活性化について誤っているものを2つ選べ。',
                    choices: ["ナイーブT細胞の活性化にはTCRからの活性化シグナルだけでは不十分であり、CD28を介した共刺激が必要である", "TCRシグナルの活性化はITAMのアセチル化によって開始される", "シクロスポリンはカルシニューリンを阻害することで、T細胞の活性化を抑制する",
                        "活性化したCD4+T細胞はIL-2を産生し、T細胞の増殖とヘルパーT細胞への分化を促す",
                        "スーパー抗原はTCRとCD28に同時に結合することで、特定のクローンの著しい活性化と増殖を引き起こす",
                        "Toxic shock syndrome(TSS)は黄色ブドウ球菌由来のスーパー抗原が原因の疾患である"
                    ],
                    answerImg: [TcellActivationSignal, superantigen],
                    answer: '2と5は誤り...TCRシグナルの活性化はFyn&LckやZAP-70のチロシン部分のリン酸化が出発点。スーパー抗原はTCRを非特異的に活性化させ、CD28は関係しない。',
                    commentary: '',
                },
                {
                    detailInfo: '0519レジュメ中',
                    questionImg: [],
                    questionSentence: 'レジュメ中のEnglish Journal of Medicineの動画を見て、次の中から正しいものを選べ',
                    choices: ["トシリズマブはIL-6に対する抗体である",
                        "トシリズマブとプラセボは同数の患者に投与された",
                        "投与された患者は全て入院患者である",
                        "トシリズマブは生存率を優位に改善させた",
                        "トシリズマブ投与群の方が有害事象が高かった"
                    ],
                    answerImg: [],
                    answer: '投与された患者は全て入院患者である',
                    commentary: 'トシリズマブTocillizumabはIL-6受容体に対する抗体で、トシリズマブ：プラセボ群は2:1の割合。トシリズマブはMortality=死亡率には全く影響を与えなかったが、重症化には数％効果があった。',
                },
                {
                    detailInfo: '0519レジュメ中',
                    questionImg: [],
                    questionSentence: 'T細胞の活性化について誤っているものを2つ選べ。',
                    choices: ["T細胞抗原受容体(TCR)α鎖/β鎖はITAM(免疫受容体チロシン活性化モチーフ)を持たないため、シグナル伝達にはCD3との会合が必要である",
                        "ナイーブT細胞はTCRシグナルのみでは活性化できずanergyを誘導する",
                        "活性化T細胞の増殖にはIL-2が必要である",
                        "Th17細胞は寄生虫感染に対する生体防御に重要である",
                        "細胞障害性T細胞から分泌されるGranzyme BはCaspaseの活性化を介して標的細胞にアポトーシスを誘導する",
                        "セントラルメモリーT細胞は、炎症が起こった臓器内で長期間生存する"
                    ],
                    answerImg: [ThDifferentiation, centralMemoryT],
                    answer: '4と6が誤り...寄生虫感染に対応するのはTh2。セントラルメモリーT(TCM)細胞は主に二次リンパ組織のT細胞領域に存在している。',
                    commentary: '',
                },

                {
                    detailInfo: '5/19小テスト(T細胞)',
                    questionImg: [],
                    questionSentence: 'T細胞が分化する臓器はどちらか？',
                    answerImg: [],
                    choices: ["骨髄", "胸腺"],
                    answer: '胸腺(Thymus)',
                    commentary: '',
                },
                {
                    detailInfo: '5/19小テスト(T細胞)',
                    questionImg: [],
                    questionSentence: 'T細胞の教育はどちらが先に行われるか？',
                    answerImg: [],
                    choices: ["正の選択", "負の選択"],
                    answer: '正の選択',
                    commentary: '皮質上皮細胞cTECによって正の選択が行われた後、髄質表皮細胞mTECによって負の選択が行われる。',
                },
                {
                    detailInfo: '5/19小テスト(T細胞)',
                    questionImg: [],
                    questionSentence: 'T細胞抗原受容体（TCR）の構成として多いのはどちらか？                    ',
                    choices: ["αβ鎖", "γδ鎖"],
                    answerImg: [],
                    answer: 'αβ鎖',
                    commentary: 'αβ鎖が90%。一般的にT細胞とよぶときはαβ型T細胞',
                },
                {
                    detailInfo: '5/19小テスト(T細胞)',
                    questionImg: [],
                    questionSentence: 'アネルギー（Anergy）の定義として、正しいのはどちらか？                    ',
                    choices: ["抗原が与えられても抗原抗体反応が起こらない状態", "抗原が与えられても抗原抗体反応が過剰に起こる状態"],
                    answerImg: [],
                    answer: '抗原が与えられても抗原抗体反応が起こらない状態',
                    commentary: '副刺激がなければ、T細胞は活性化されない。',
                },
                {
                    detailInfo: '5/19小テスト(T細胞)',
                    questionImg: [],
                    questionSentence: 'T細胞の活性化に必須な酵素はどちらか？                    ',
                    choices: ["チロシンキナーゼ", "ヒスチジンキナーゼ"],
                    answerImg: [],
                    answer: 'チロシンキナーゼ',
                    commentary: 'T細胞の活性化は、チロシン部分のリン酸化から開始される。',
                },
                {
                    detailInfo: '5/19小テスト(T細胞)',
                    questionImg: [],
                    questionSentence: 'T細胞の増殖・活性化に働くサイトカインはどちらか？                    ',
                    choices: ["IL-1", "IL-2"],
                    answerImg: [],
                    answer: 'IL-2',
                    commentary: 'T細胞の分化に関わるサイトカインとは別',
                },
                {
                    detailInfo: '5/19小テスト(T細胞)',
                    questionImg: [],
                    questionSentence: '肉芽腫形成に関わるマクロファージはどちらか？                    ',
                    choices: ["ランゲルハンス細胞", "類上皮細胞"],
                    answerImg: [],
                    answer: '類上皮細胞',
                    commentary: 'マクロファージは肉芽腫の中でラングハンス巨細胞や類上皮細胞として認められる。',
                },
                {
                    detailInfo: '5/19小テスト(T細胞)',
                    questionImg: [],
                    questionSentence: '先進国におけるアレルギー増加の原因を説明した仮説はどちらか？                    ',
                    choices: ["衛生仮説", "抗原仮説"],
                    answerImg: [],
                    answer: '衛生仮説',
                    commentary: '抗原仮説は存在しない。',
                },
                {
                    detailInfo: '5/19小テスト(T細胞)',
                    questionImg: [],
                    questionSentence: '制御性T細胞に特異的な転写因子はどちらか？                    ',
                    choices: ["Foxp3", "T-bet"],
                    answerImg: [],
                    answer: 'Foxp3',
                    commentary: '制御性T細胞：Tregは免疫を抑制する作用を持っていて、分化に必要なFoxp3遺伝子に変異があると自己免疫疾患IPEXを引き起こす',
                },
                {
                    detailInfo: '5/26出席確認',
                    questionImg: [],
                    questionSentence: '補体反応で最も早く活性化されるのは？',
                    choices: ["古典経路", "代替経路", "レクチン経路"],
                    answerImg: [],
                    answer: '代替経路',
                    commentary: '基本的に常時体の中で活性化されている。',
                },
                {
                    detailInfo: '5/26出席確認',
                    questionImg: [],
                    questionSentence: '古典経路のＣ５転換酵素は？',
                    answerImg: [],
                    choices: ["C3bBb3b", "C4b2a3b"],
                    answer: 'C4b2a3b',
                    commentary: '古典経路・レクチン経路で、C5転換酵素として作用する。C3,C4,C5は分解されるとaが遊離されるが、C2はC2bが遊離する。',
                },
                {
                    detailInfo: '5/26出席確認',
                    questionImg: [],
                    questionSentence: '胎盤脱落膜に多いリンパ球はどれか',
                    choices: ["NK細胞", "T細胞", "B細胞"],
                    answerImg: [],
                    answer: 'NK細胞',
                    commentary: '',
                },
                {
                    detailInfo: '5/26出席確認',
                    questionImg: [],
                    questionSentence: '胎盤トロホブラストに発現していないHLAクラスＩ分子はどれか ',
                    choices: ["HLA-G", "HLA-A", "HLA-C"],
                    answerImg: [],
                    answer: 'HLA-A',
                    commentary: '発現して「いない」。HLA-CやHLA-Gは胎盤トロホブラストで発現して、胎児の免疫学的拒絶の抑制作用に寄与している。',
                },
                // {
                //   detailInfo: '',
                //   questionImg: [],
                //   questionSentence:
                //     '',
                //   answerImg: [],
                //   answer: '',
                //   commentary: '',
                // },

            ],
        },
        {
            groupTag: 'レポート課題',
            groupContents: [{
                    detailInfo: '4/14',
                    questionImg: [],
                    questionSentence: '下記の pattern recognition receptor (PRR)のリガンドである pathogen associated molecular pattern (PAMPs)ならびに代表的な病原体を列挙せよ。 (1)TLR2',
                    answerImg: [TLR, TLRpattern],
                    answer: 'PAMPs：ペプチドグリカン・リポタイコ酸。代表的な病原体：グラム陽性菌（肺炎球菌・黄色ブドウ球菌・溶連菌・ジフテリア菌など）',
                    commentary: 'ペプチドグリカン・リポタイコ酸はグラム陽性菌の厚い細胞壁特有の物質。グラム陽性菌には外膜はない。',
                },
                {
                    detailInfo: '4/14',
                    questionImg: [],
                    questionSentence: '下記の pattern recognition receptor (PRR)のリガンドである pathogen associated molecular pattern (PAMPs)ならびに代表的な病原体を列挙せよ。 (2)TLR4',
                    answerImg: [TLR, LPS],
                    answer: 'PAMPs：LSPなど。代表的な病原体：グラム陰性菌（大腸菌・サルモネラ菌・緑膿菌・淋菌など）',
                    commentary: 'LPSはグラム陰性菌の外膜成分。グラム陰性菌は細胞壁が薄い。',
                },
                {
                    detailInfo: '4/14',
                    questionImg: [],
                    questionSentence: '下記の pattern recognition receptor (PRR)のリガンドである pathogen associated molecular pattern (PAMPs)ならびに代表的な病原体を列挙せよ。 (3)RIG-I like receptor',
                    answerImg: [RLR],
                    answer: 'PAMPs：ウイルス由来RNA。代表的な病原体：RNAウイルス（インフルエンザウイルス・コロナウイルス・C型肝炎ウイルスなど）',
                    commentary: 'RLGに受容されることによって、炎症性サイトカインやIFN-β含むⅠ型インターフェロンの分泌が刺激される。',
                },
                {
                    detailInfo: '4/14',
                    questionImg: [],
                    questionSentence: 'サイトカインの定義とその特徴（5つ以上）を述べよ',
                    answerImg: [],
                    answer: '【定義】細胞が産生する微量生理活性タンパク質の総称。【特徴】1.多くは低分子糖たんぱく質である。2.主に産生局所で働く。3.きわめて微量で効果を発揮する。4.細胞表面に発現する特異的な受容体に結合し、効果を発揮する。5.多様な生理活性を持つ。6.異なるサイトカインが同じ活性を示す（重複性）。7.種々のサイトカイン間で相互依存性がある（サイトカインネットワーク）。',
                    commentary: '',
                },
                {
                    detailInfo: '5/19',
                    questionImg: [],
                    questionSentence: '胸腺でのT細胞の分化過程について、なぜ正の選択と負の選択が必要なのか述べよ',
                    answerImg: [TcellEducation],
                    answer: '',
                    commentary: '',
                },
                {
                    detailInfo: '5/19',
                    questionImg: [],
                    questionSentence: 'αβT細胞とγδT細胞との違いについて述べよ。',
                    answerImg: [TcellGammaDelta, TCRSegments],
                    answer: '',
                    commentary: 'T細胞抗原受容体にはαβ型（90%）とγδ型(10%)があり、γδT細胞はリンパ球ストレス（細胞障害）監視機構と呼ばれる生体防御反応担う中心的な細胞である。細菌感染やウイルス感染などの外からのストレスに加えて、がん化に伴う細胞の変化に対しても敏感に感知することが可能。',
                },
                {
                    detailInfo: '5/19',
                    questionImg: [],
                    questionSentence: 'Tregの抑制的制御のメカニズムを述べよ。',
                    answerImg: [Treg],
                    answer: '',
                    commentary: '1.抗原提示細胞のCD80/CD86の発現を低く抑える。2.高親和性のIL-2受容体によってほかのT細胞からIL-2を奪って活性化を妨げる',
                },
                // {
                //   detailInfo: '',
                //   questionImg: [],
                //   questionSentence: '',
                //   answerImg: [],
                //   answer: '',
                //   commentary: '',
                // },
            ],
        },
    ])
    const showQuestionList = () => {
        return questionList
    }
    return {
        showQuestionList,
        appName,
        jpName,
    }
}